version: "3"
services:
  redis:
    image: redis
    networks:
      - webnet
  db:
    image: postgres
    ports:
      - "3030:5432"
    networks:
      - webnet
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: paty
      POSTGRES_DB: slack
  web:
    image: slack-clone-server
    networks:
      - webnet
    depends_on:
      - db
      - redis
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: paty
      POSTGRES_DB: slack
      DB_HOST: db
      REDIS_HOST: redis
    command: ["node", "index.js"]
  nginx:
    image: nginx
    networks:
      - webnet
    depends_on:
      - web
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
    ports:
      - "8081:80"
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
networks:
  webnet: